services:
  - type: web
    name: invoice-generator-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build:server
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /
    autoDeploy: true
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: invoice-generator-disk
      size: 1GB
      mountPath: /opt/render/project/src/invoices